//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test3_lttq
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phim
    {
        public string madon { get; set; }
        public string tenphim { get; set; }
        public string quocgia { get; set; }
        public string theloai { get; set; }
        public Nullable<System.DateTime> NCC { get; set; }
        public Nullable<int> dotuoi { get; set; }
    
        public virtual phim2d phim2d { get; set; }
        public virtual phim3d phim3d { get; set; }
    }
}
