//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ontap
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVienBanHang
    {
        public string MaNhanVien { get; set; }
        public Nullable<double> DoanhSo { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
